%% generated by soap from: /Users/dragosdumitru/Work/google-multi/priv/campaign.wsdl
%% for service "CampaignService" and port "CampaignServiceInterfacePort"
%% using options: [{service,"CampaignService"},{port,"CampaignServiceInterfacePort"},{generate,client},{namespaces,[{"https://adwords.google.com/api/adwords/cm/v201809",undefined}]},{generate_tests,none},{http_client,soap_client_inets},{client_name,"campaign_service_client"},{strict,true}]

-module(campaign_service_client).

-include("campaign.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export([get/3]).
-export([mutate/3]).
-export([mutateLabel/3]).
-export([query/3]).

-spec get(Soap_body::get(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(getResponse()).
get(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutate(Soap_body::mutate(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateResponse()).
mutate(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutateLabel(Soap_body::mutateLabel(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateLabelResponse()).
mutateLabel(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec query(Soap_body::query(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(queryResponse()).
query(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.