%% generated by soap from: /Users/dragosdumitru/Work/google-multi/priv/customer.wsdl
%% for service "CustomerService" and port "CustomerServiceInterfacePort"
%% using options: [{service,"CustomerService"},{port,"CustomerServiceInterfacePort"},{generate,client},{namespaces,[{"https://adwords.google.com/api/adwords/cm/v201809",undefined}]},{generate_tests,none},{http_client,soap_client_inets},{client_name,"customer_client"},{strict,true}]

-module(customer_client).

-include("customer.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export([getCustomers/3]).
-export([getServiceLinks/3]).
-export([mutate/3]).
-export([mutateServiceLinks/3]).

-spec getCustomers(Soap_body::getCustomers(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(getCustomersResponse()).
getCustomers(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec getServiceLinks(Soap_body::getServiceLinks(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(getServiceLinksResponse()).
getServiceLinks(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutate(Soap_body::mutate(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateResponse()).
mutate(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutateServiceLinks(Soap_body::mutateServiceLinks(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateServiceLinksResponse()).
mutateServiceLinks(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.