%% generated by soap from: /Users/dragosdumitru/Work/google-multi/priv/managed_customer.wsdl
%% for service "ManagedCustomerService" and port "ManagedCustomerServiceInterfacePort"
%% using options: [{service,"ManagedCustomerService"},{port,"ManagedCustomerServiceInterfacePort"},{generate,client},{namespaces,[{"https://adwords.google.com/api/adwords/mcm/v201809",undefined}]},{generate_tests,none},{http_client,soap_client_inets},{client_name,"managed_customer_service_client"},{strict,true}]

-module(managed_customer_service_client).

-include("managed_customer.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export([get/3]).
-export([getPendingInvitations/3]).
-export([mutate/3]).
-export([mutateLabel/3]).
-export([mutateLink/3]).
-export([mutateManager/3]).

-spec get(Soap_body::get(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(getResponse()).
get(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec getPendingInvitations(Soap_body::getPendingInvitations(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(getPendingInvitationsResponse()).
getPendingInvitations(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutate(Soap_body::mutate(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateResponse()).
mutate(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutateLabel(Soap_body::mutateLabel(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateLabelResponse()).
mutateLabel(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutateLink(Soap_body::mutateLink(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateLinkResponse()).
mutateLink(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec mutateManager(Soap_body::mutateManager(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response(mutateManagerResponse()).
mutateManager(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.